image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main
    - junit4
    - Testng
build: off

install:

  - java -jar ./artifacts/app-mbank.jar &
  - chmod +x gradlew

build_script:
  - chmod +x gradlew
  - ./gradlew test --info